// front-end-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Angular 15 Quan App';
}

<div>
  <nav class="navbar navbar-expand navbar-light bg-light">
    <a href="#" class="navbar-brand">Milestone Project</a>
    <div class="navbar-nav">
      <li class="nav-item">
        <a routerLink="books" class="nav-link">Books</a>
      </li>
      <li class="nav-item">
        <a routerLink="add" class="nav-link">Add a new book</a>
      </li>
    </div>
  </nav>

  <div class="container mt-3">
    <router-outlet></router-outlet>
  </div>
</div>

// front-end-react/src/App.js
import React, { Component } from "react";
import { Routes, Route, Link } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import "./App.css";

import AddBook from "./components/add-book.component";
import Book from "./components/book.component";
import BooksList from "./components/books-list.component";

class App extends Component {
  render() {
    return (
      <div>
        <nav className="navbar navbar-expand navbar-dark bg-dark">
          <Link to={"/books"} className="navbar-brand">
            Online Book Library
          </Link>
          <div className="navbar-nav mr-auto">
            <li className="nav-item">
              <Link to={"/books"} className="nav-link">
              Books
              </Link>
            </li>
            <li className="nav-item">
              <Link to={"/add"} className="nav-link">
                Add
              </Link>
            </li>
          </div>
        </nav>

        <div className="container mt-3">
          <Routes>
            <Route path="/" element={<BooksList/>} />
            <Route path="/books" element={<BooksList/>} />
            <Route path="/add" element={<AddBook/>} />
            <Route path="/books/:id" element={<Book/>} />
          </Routes>
        </div>
      </div>
    );
  }
}

export default App;
